# Exploratory Data Analyis(EDA) and Data Cleaning

###### In this notebook the following tasks  performed
* Loading the dataset
* Data understanding
* Data preprocessing
    * null values check and handled
    * handling categorical values
    * other preprocesing task
* save the cleaned data to the folder

In [30]:
# importing neccessary packages 
import sys
import os
import pandas as pd
import numpy as np
import seaborn as sns
import warnings
import plot
warnings.filterwarnings('ignore')
import matplotlib.pyplot as plt

In [31]:
# Import our python scripts
sys.path.append(os.path.abspath(os.path.join('../scripts')))
from data_info import DataFrameInfo
from data_cleaning import DataFrameCleaning

In [32]:
#loading original dataset
pd.set_option('display.max_columns', None)
pd.options.display.float_format = "{:.3f}".format
df = pd.read_csv('../data/Week1_challenge_data_source(CSV) .csv', na_values=['?', None])
df.head()

,Bearer Id,Start,Start ms,End,End ms,Dur. (ms),IMSI,MSISDN/Number,IMEI,Last Location Name,Avg RTT DL (ms),Avg RTT UL (ms),Avg Bearer TP DL (kbps),Avg Bearer TP UL (kbps),TCP DL Retrans. Vol (Bytes),TCP UL Retrans. Vol (Bytes),DL TP < 50 Kbps (%),50 Kbps < DL TP < 250 Kbps (%),250 Kbps < DL TP < 1 Mbps (%),DL TP > 1 Mbps (%),UL TP < 10 Kbps (%),10 Kbps < UL TP < 50 Kbps (%),50 Kbps < UL TP < 300 Kbps (%),UL TP > 300 Kbps (%),HTTP DL (Bytes),HTTP UL (Bytes),Activity Duration DL (ms),Activity Duration UL (ms),Dur. (ms).1,Handset Manufacturer,Handset Type,Nb of sec with 125000B < Vol DL,Nb of sec with 1250B < Vol UL < 6250B,Nb of sec with 31250B < Vol DL < 125000B,Nb of sec with 37500B < Vol UL,Nb of sec with 6250B < Vol DL < 31250B,Nb of sec with 6250B < Vol UL < 37500B,Nb of sec with Vol DL < 6250B,Nb of sec with Vol UL < 1250B,Social Media DL (Bytes),Social Media UL (Bytes),Google DL (Bytes),Google UL (Bytes),Email DL (Bytes),Email UL (Bytes),Youtube DL (Bytes),Youtube UL (Bytes),Netflix DL (Bytes),Netflix UL (Bytes),Gaming DL (Bytes),Gaming UL (Bytes),Other DL (Bytes),Other UL (Bytes),Total UL (Bytes),Total DL (Bytes)
0,13114483460844900352.000,4/4/2019 12:01,770.000,4/25/2019 14:35,662.000,1823652.000,208201448079117.000,33664962239.000,35521209507511.000,9.16456699548519E+015,42.000,5.000,23.000,44.000,NaN,NaN,100.000,0.000,0.000,0.000,100.000,0.000,0.000,0.000,NaN,NaN,37624.000,38787.000,1823652892.000,Samsung,Samsung Galaxy A5 Sm-A520F,NaN,NaN,NaN,NaN,NaN,NaN,213.000,214.000,1545765.000,24420.000,1634479.000,1271433.000,3563542.000,137762.000,15854611.000,2501332.000,8198936.000,9656251.000,278082303.000,14344150.000,171744450.000,8814393.000,36749741.000,308879636.000
1,13114483482878900224.000,4/9/2019 13:04,235.000,4/25/2019 8:15,606.000,1365104.000,208201909211140.000,33681854413.000,35794009006359.000,L77566A,65.000,5.000,16.000,26.000,NaN,NaN,100.000,0.000,0.000,0.000,100.000,0.000,0.000,0.000,NaN,NaN,168.000,3560.000,1365104371.000,Samsung,Samsung Galaxy J5 (Sm-J530),NaN,NaN,NaN,NaN,NaN,NaN,971.000,1022.000,1926113.000,7165.000,3493924.000,920172.000,629046.000,308339.000,20247395.000,19111729.000,18338413.000,17227132.000,608750074.000,1170709.000,526904238.000,15055145.000,53800391.000,653384965.000
2,13114483484080500736.000,4/9/2019 17:42,1.000,4/25/2019 11:58,652.000,1361762.000,208200314458056.000,33760627129.000,35281510359387.000,D42335A,NaN,NaN,6.000,9.000,NaN,NaN,100.000,0.000,0.000,0.000,100.000,0.000,0.000,0.000,NaN,NaN,0.000,0.000,1361762651.000,Samsung,Samsung Galaxy A8 (2018),NaN,NaN,NaN,NaN,NaN,NaN,751.000,695.000,1684053.000,42224.000,8535055.000,1694064.000,2690151.000,672973.000,19725661.000,14699576.000,17587794.000,6163408.000,229584621.000,395630.000,410692588.000,4215763.000,27883638.000,279807335.000
3,13114483485442799616.000,4/10/2019 0:31,486.000,4/25/2019 7:36,171.000,1321509.000,208201402342131.000,33750343200.000,35356610164913.000,T21824A,NaN,NaN,44.000,44.000,NaN,NaN,100.000,0.000,0.000,0.000,100.000,0.000,0.000,0.000,NaN,NaN,3330.000,37882.000,1321509685.000,undefined,undefined,NaN,NaN,NaN,NaN,NaN,NaN,17.000,207.000,644121.000,13372.000,9023734.000,2788027.000,1439754.000,631229.000,21388122.000,15146643.000,13994646.000,1097942.000,799538153.000,10849722.000,749039933.000,12797283.000,43324218.000,846028530.000
4,13114483499480700928.000,4/12/2019 20:10,565.000,4/25/2019 10:40,954.000,1089009.000,208201401415120.000,33699795932.000,35407009745539.000,D88865A,NaN,NaN,6.000,9.000,NaN,NaN,100.000,0.000,0.000,0.000,100.000,0.000,0.000,0.000,NaN,NaN,0.000,0.000,1089009389.000,Samsung,Samsung Sm-G390F,NaN,NaN,NaN,NaN,NaN,NaN,607.000,604.000,862600.000,50188.000,6248284.000,1500559.000,1936496.000,173853.000,15259380.000,18962873.000,17124581.000,415218.000,527707248.000,3529801.000,550709500.000,13910322.000,38542814.000,569138589.000

## Telcom Data Informations
* cloumns name
* number of datapoints
* number of columns and etc

In [33]:
# columns name
df.columns.tolist()

['Bearer Id',
 'Start',
 'Start ms',
 'End',
 'End ms',
 'Dur. (ms)',
 'IMSI',
 'MSISDN/Number',
 'IMEI',
 'Last Location Name',
 'Avg RTT DL (ms)',
 'Avg RTT UL (ms)',
 'Avg Bearer TP DL (kbps)',
 'Avg Bearer TP UL (kbps)',
 'TCP DL Retrans. Vol (Bytes)',
 'TCP UL Retrans. Vol (Bytes)',
 'DL TP < 50 Kbps (%)',
 '50 Kbps < DL TP < 250 Kbps (%)',
 '250 Kbps < DL TP < 1 Mbps (%)',
 'DL TP > 1 Mbps (%)',
 'UL TP < 10 Kbps (%)',
 '10 Kbps < UL TP < 50 Kbps (%)',
 '50 Kbps < UL TP < 300 Kbps (%)',
 'UL TP > 300 Kbps (%)',
 'HTTP DL (Bytes)',
 'HTTP UL (Bytes)',
 'Activity Duration DL (ms)',
 'Activity Duration UL (ms)',
 'Dur. (ms).1',
 'Handset Manufacturer',
 'Handset Type',
 'Nb of sec with 125000B < Vol DL',
 'Nb of sec with 1250B < Vol UL < 6250B',
 'Nb of sec with 31250B < Vol DL < 125000B',
 'Nb of sec with 37500B < Vol UL',
 'Nb of sec with 6250B < Vol DL < 31250B',
 'Nb of sec with 6250B < Vol UL < 37500B',
 'Nb of sec with Vol DL < 6250B',
 'Nb of sec with Vol UL < 1250B',
 'Social Media DL (Bytes)',
 'Social Media UL (Bytes)',
 'Google DL (Bytes)',
 'Google UL (Bytes)',
 'Email DL (Bytes)',
 'Email UL (Bytes)',
 'Youtube DL (Bytes)',
 'Youtube UL (Bytes)',
 'Netflix DL (Bytes)',
 'Netflix UL (Bytes)',
 'Gaming DL (Bytes)',
 'Gaming UL (Bytes)',
 'Other DL (Bytes)',
 'Other UL (Bytes)',
 'Total UL (Bytes)',
 'Total DL (Bytes)']

In [34]:
#to check number of data points 
print(f" There are : {df.shape[0]} rows and {df.shape[1]} columns")

 There are : 150001 rows and 55 columns

In [35]:
# Instantiate DataFrameInfo classes for getting information about the data 
data_info = DataFrameInfo(df)

# to check detail about data
data_info.detail_info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150001 entries, 0 to 150000
Data columns (total 55 columns):
 #   Column                                    Non-Null Count   Dtype
---  ------                                    --------------   -----
 0   Bearer Id                                 149010 non-null  float64
 1   Start                                     150000 non-null  object
 2   Start ms                                  150000 non-null  float64
 3   End                                       150000 non-null  object
 4   End ms                                    150000 non-null  float64
 5   Dur. (ms)                                 150000 non-null  float64
 6   IMSI                                      149431 non-null  float64
 7   MSISDN/Number                             148935 non-null  float64
 8   IMEI                                      149429 non-null  float64
 9   Last Location Name                        148848 non-null  object
 10  Avg RTT DL (ms)                           122172 non-null  float64
 11  Avg RTT UL (ms)                           122189 non-null  float64
 12  Avg Bearer TP DL (kbps)                   150000 non-null  float64
 13  Avg Bearer TP UL (kbps)                   150000 non-null  float64
 14  TCP DL Retrans. Vol (Bytes)               61855 non-null   float64
 15  TCP UL Retrans. Vol (Bytes)               53352 non-null   float64
 16  DL TP < 50 Kbps (%)                       149247 non-null  float64
 17  50 Kbps < DL TP < 250 Kbps (%)            149247 non-null  float64
 18  250 Kbps < DL TP < 1 Mbps (%)             149247 non-null  float64
 19  DL TP > 1 Mbps (%)                        149247 non-null  float64
 20  UL TP < 10 Kbps (%)                       149209 non-null  float64
 21  10 Kbps < UL TP < 50 Kbps (%)             149209 non-null  float64
 22  50 Kbps < UL TP < 300 Kbps (%)            149209 non-null  float64
 23  UL TP > 300 Kbps (%)                      149209 non-null  float64
 24  HTTP DL (Bytes)                           68527 non-null   float64
 25  HTTP UL (Bytes)                           68191 non-null   float64
 26  Activity Duration DL (ms)                 150000 non-null  float64
 27  Activity Duration UL (ms)                 150000 non-null  float64
 28  Dur. (ms).1                               150000 non-null  float64
 29  Handset Manufacturer                      149429 non-null  object
 30  Handset Type                              149429 non-null  object
 31  Nb of sec with 125000B < Vol DL           52463 non-null   float64
 32  Nb of sec with 1250B < Vol UL < 6250B     57107 non-null   float64
 33  Nb of sec with 31250B < Vol DL < 125000B  56415 non-null   float64
 34  Nb of sec with 37500B < Vol UL            19747 non-null   float64
 35  Nb of sec with 6250B < Vol DL < 31250B    61684 non-null   float64
 36  Nb of sec with 6250B < Vol UL < 37500B    38158 non-null   float64
 37  Nb of sec with Vol DL < 6250B             149246 non-null  float64
 38  Nb of sec with Vol UL < 1250B             149208 non-null  float64
 39  Social Media DL (Bytes)                   150001 non-null  float64
 40  Social Media UL (Bytes)                   150001 non-null  float64
 41  Google DL (Bytes)                         150001 non-null  float64
 42  Google UL (Bytes)                         150001 non-null  float64
 43  Email DL (Bytes)                          150001 non-null  float64
 44  Email UL (Bytes)                          150001 non-null  float64
 45  Youtube DL (Bytes)                        150001 non-null  float64
 46  Youtube UL (Bytes)                        150001 non-null  float64
 47  Netflix DL (Bytes)                        150001 non-null  float64
 48  Netflix UL (Bytes)                        150001 non-null  float64
 49  Gaming DL (Bytes)                         150001 non-null  float64
 50  Gaming UL (Bytes)                         150001 non-null  float64
 51  Other DL (Bytes)                          150001 non-null  float64
 52  Other UL (Bytes)                          150001 non-null  float64
 53  Total UL (Bytes)                          150000 non-null  float64
 54  Total DL (Bytes)                          150000 non-null  float64
dtypes: float64(50), object(5)
memory usage: 62.9+ MB
None

In [36]:
# how many missing values exists or better still what is the % of missing values in the dataset?
def percent_missing(df):
    # to calcualte total number of cells in dataframe
    totalCells=np.product(df.shape)
    # to count number of missing values percloumns
    missingCount=df.isnull().sum()
    # to calculate total number of missing values
    totalMissing=missingCount.sum()
    # to calucalte percentage of missing values 
    print("The Telecom dataset contains",round(((totalMissing/totalCells)*100),2),"%","missing values.")
percent_missing(df)

The Telecom dataset contains 12.5 % missing values.

In [37]:
# Geting which column has missing values 
df.isnull().sum()

Bearer Id                                      991
Start                                            1
Start ms                                         1
End                                              1
End ms                                           1
Dur. (ms)                                        1
IMSI                                           570
MSISDN/Number                                 1066
IMEI                                           572
Last Location Name                            1153
Avg RTT DL (ms)                              27829
Avg RTT UL (ms)                              27812
Avg Bearer TP DL (kbps)                          1
Avg Bearer TP UL (kbps)                          1
TCP DL Retrans. Vol (Bytes)                  88146
TCP UL Retrans. Vol (Bytes)                  96649
DL TP < 50 Kbps (%)                            754
50 Kbps < DL TP < 250 Kbps (%)                 754
250 Kbps < DL TP < 1 Mbps (%)                  754
DL TP > 1 Mbps (%)                             754
UL TP < 10 Kbps (%)                            792
10 Kbps < UL TP < 50 Kbps (%)                  792
50 Kbps < UL TP < 300 Kbps (%)                 792
UL TP > 300 Kbps (%)                           792
HTTP DL (Bytes)                              81474
HTTP UL (Bytes)                              81810
Activity Duration DL (ms)                        1
Activity Duration UL (ms)                        1
Dur. (ms).1                                      1
Handset Manufacturer                           572
Handset Type                                   572
Nb of sec with 125000B < Vol DL              97538
Nb of sec with 1250B < Vol UL < 6250B        92894
Nb of sec with 31250B < Vol DL < 125000B     93586
Nb of sec with 37500B < Vol UL              130254
Nb of sec with 6250B < Vol DL < 31250B       88317
Nb of sec with 6250B < Vol UL < 37500B      111843
Nb of sec with Vol DL < 6250B                  755
Nb of sec with Vol UL < 1250B                  793
Social Media DL (Bytes)                          0
Social Media UL (Bytes)                          0
Google DL (Bytes)                                0
Google UL (Bytes)                                0
Email DL (Bytes)                                 0
Email UL (Bytes)                                 0
Youtube DL (Bytes)                               0
Youtube UL (Bytes)                               0
Netflix DL (Bytes)                               0
Netflix UL (Bytes)                               0
Gaming DL (Bytes)                                0
Gaming UL (Bytes)                                0
Other DL (Bytes)                                 0
Other UL (Bytes)                                 0
Total UL (Bytes)                                 1
Total DL (Bytes)                                 1
dtype: int64

In [38]:
# Check the percentage of missing values in each column

percent_missing = df.isnull().sum() * 100 / len(df)
missing_value_df = pd.DataFrame({'percent_missing': percent_missing})
print(missing_value_df)

                                          percent_missing
Bearer Id                                           0.661
Start                                               0.001
Start ms                                            0.001
End                                                 0.001
End ms                                              0.001
Dur. (ms)                                           0.001
IMSI                                                0.380
MSISDN/Number                                       0.711
IMEI                                                0.381
Last Location Name                                  0.769
Avg RTT DL (ms)                                    18.553
Avg RTT UL (ms)                                    18.541
Avg Bearer TP DL (kbps)                             0.001
Avg Bearer TP UL (kbps)                             0.001
TCP DL Retrans. Vol (Bytes)                        58.764
TCP UL Retrans. Vol (Bytes)                        64.432
DL TP < 50 Kbps (%)                                 0.503
50 Kbps < DL TP < 250 Kbps (%)                      0.503
250 Kbps < DL TP < 1 Mbps (%)                       0.503
DL TP > 1 Mbps (%)                                  0.503
UL TP < 10 Kbps (%)                                 0.528
10 Kbps < UL TP < 50 Kbps (%)                       0.528
50 Kbps < UL TP < 300 Kbps (%)                      0.528
UL TP > 300 Kbps (%)                                0.528
HTTP DL (Bytes)                                    54.316
HTTP UL (Bytes)                                    54.540
Activity Duration DL (ms)                           0.001
Activity Duration UL (ms)                           0.001
Dur. (ms).1                                         0.001
Handset Manufacturer                                0.381
Handset Type                                        0.381
Nb of sec with 125000B < Vol DL                    65.025
Nb of sec with 1250B < Vol UL < 6250B              61.929
Nb of sec with 31250B < Vol DL < 125000B           62.390
Nb of sec with 37500B < Vol UL                     86.835
Nb of sec with 6250B < Vol DL < 31250B             58.878
Nb of sec with 6250B < Vol UL < 37500B             74.562
Nb of sec with Vol DL < 6250B                       0.503
Nb of sec with Vol UL < 1250B                       0.529
Social Media DL (Bytes)                             0.000
Social Media UL (Bytes)                             0.000
Google DL (Bytes)                                   0.000
Google UL (Bytes)                                   0.000
Email DL (Bytes)                                    0.000
Email UL (Bytes)                                    0.000
Youtube DL (Bytes)                                  0.000
Youtube UL (Bytes)                                  0.000
Netflix DL (Bytes)                                  0.000
Netflix UL (Bytes)                                  0.000
Gaming DL (Bytes)                                   0.000
Gaming UL (Bytes)                                   0.000
Other DL (Bytes)                                    0.000
Other UL (Bytes)                                    0.000
Total UL (Bytes)                                    0.001
Total DL (Bytes)                                    0.001

In [39]:
#To check for skew in data:
#based on rule of thumb if the skewness is b/n 
#-0.5  and  0.5 ---->fairly symmetrical
# 1 and – 0.5 or between 0.5 and 1, the data are moderately skewed
# less than -1 or  greater than 1, the data are highly skewed.
data_info.skewness()
#To check for skew in data:
#df.skew().sort_values(ascending=False)

Bearer Id                                    0.027
Start ms                                     0.001
End ms                                      -0.001
Dur. (ms)                                    3.953
IMSI                                        41.046
MSISDN/Number                              332.156
IMEI                                         1.071
Avg RTT DL (ms)                             62.908
Avg RTT UL (ms)                             28.457
Avg Bearer TP DL (kbps)                      2.589
Avg Bearer TP UL (kbps)                      4.503
TCP DL Retrans. Vol (Bytes)                 15.952
TCP UL Retrans. Vol (Bytes)                 84.113
DL TP < 50 Kbps (%)                         -2.298
50 Kbps < DL TP < 250 Kbps (%)               3.271
250 Kbps < DL TP < 1 Mbps (%)                4.566
DL TP > 1 Mbps (%)                           5.370
UL TP < 10 Kbps (%)                         -8.985
10 Kbps < UL TP < 50 Kbps (%)               10.944
50 Kbps < UL TP < 300 Kbps (%)              21.878
UL TP > 300 Kbps (%)                        36.174
HTTP DL (Bytes)                             38.945
HTTP UL (Bytes)                             32.475
Activity Duration DL (ms)                    5.872
Activity Duration UL (ms)                    7.383
Dur. (ms).1                                  3.953
Nb of sec with 125000B < Vol DL              6.593
Nb of sec with 1250B < Vol UL < 6250B       22.036
Nb of sec with 31250B < Vol DL < 125000B     6.611
Nb of sec with 37500B < Vol UL              21.560
Nb of sec with 6250B < Vol DL < 31250B       6.896
Nb of sec with 6250B < Vol UL < 37500B      19.643
Nb of sec with Vol DL < 6250B                9.042
Nb of sec with Vol UL < 1250B                7.495
Social Media DL (Bytes)                     -0.002
Social Media UL (Bytes)                     -0.000
Google DL (Bytes)                           -0.008
Google UL (Bytes)                            0.002
Email DL (Bytes)                            -0.002
Email UL (Bytes)                             0.007
Youtube DL (Bytes)                           0.000
Youtube UL (Bytes)                          -0.001
Netflix DL (Bytes)                          -0.002
Netflix UL (Bytes)                          -0.000
Gaming DL (Bytes)                           -0.003
Gaming UL (Bytes)                           -0.002
Other DL (Bytes)                             0.001
Other UL (Bytes)                             0.001
Total UL (Bytes)                            -0.002
Total DL (Bytes)                            -0.003
dtype: float64

## Cleaning Data

In [42]:
# Instantiate DataFrameCleaning classes to clean the data 

clean_data = DataFrameCleaning(df)

Automation in Action...!!!

In [43]:
# Get the list of columns having more than 30% of null values

bad_columns = clean_data.get_column_with_many_null()
print("List Of Columns with More than 30% of Null Values")
print(bad_columns)
df.shape

List Of Columns with More than 30% of Null Values
['TCP DL Retrans. Vol (Bytes)', 'TCP UL Retrans. Vol (Bytes)', 'HTTP DL (Bytes)', 'HTTP UL (Bytes)', 'Nb of sec with 125000B < Vol DL', 'Nb of sec with 1250B < Vol UL < 6250B', 'Nb of sec with 31250B < Vol DL < 125000B', 'Nb of sec with 37500B < Vol UL', 'Nb of sec with 6250B < Vol DL < 31250B', 'Nb of sec with 6250B < Vol UL < 37500B']

(150001, 55)

## Missing values Handling
##### Based on the above code some columns have missing values it need the way to handle it
* missing values are handled by differnt techniques like
    * rule of thumb
    * mode,mean and median method
    * fill-forward,backward-fill etc

In [44]:
# Remove bad columns and duplicated Dur. (ms) column
clean_data.drop_columns(bad_columns)
clean_data.drop_columns('Dur. (ms).1')

In [45]:
# Remove rows with smaller null values

clean_data.drop_rows(['Bearer Id', 'IMSI'])

In [46]:
#Fill null categorical columns with Mode 

columns = ['Last Location Name', 'IMEI', 'MSISDN/Number', 'Handset Type', 'Handset Manufacturer']
clean_data.fill_categorical_columns(columns)

In [47]:
null_info = DataFrameInfo(clean_data.df)
null_info.get_null_counts()

Bearer Id                             0
Start                                 0
Start ms                              0
End                                   0
End ms                                0
Dur. (ms)                             0
IMSI                                  0
MSISDN/Number                         0
IMEI                                  0
Last Location Name                    0
Avg RTT DL (ms)                   27685
Avg RTT UL (ms)                   27666
Avg Bearer TP DL (kbps)               0
Avg Bearer TP UL (kbps)               0
DL TP < 50 Kbps (%)                 716
50 Kbps < DL TP < 250 Kbps (%)      716
250 Kbps < DL TP < 1 Mbps (%)       716
DL TP > 1 Mbps (%)                  716
UL TP < 10 Kbps (%)                 770
10 Kbps < UL TP < 50 Kbps (%)       770
50 Kbps < UL TP < 300 Kbps (%)      770
UL TP > 300 Kbps (%)                770
Activity Duration DL (ms)             0
Activity Duration UL (ms)             0
Handset Manufacturer                  0
Handset Type                          0
Nb of sec with Vol DL < 6250B       717
Nb of sec with Vol UL < 1250B       771
Social Media DL (Bytes)               0
Social Media UL (Bytes)               0
Google DL (Bytes)                     0
Google UL (Bytes)                     0
Email DL (Bytes)                      0
Email UL (Bytes)                      0
Youtube DL (Bytes)                    0
Youtube UL (Bytes)                    0
Netflix DL (Bytes)                    0
Netflix UL (Bytes)                    0
Gaming DL (Bytes)                     0
Gaming UL (Bytes)                     0
Other DL (Bytes)                      0
Other UL (Bytes)                      0
Total UL (Bytes)                      0
Total DL (Bytes)                      0
dtype: int64

In [48]:
# Fill null numerical columns with mean and median based on the column skewness value

column_list = pd.isnull(clean_data.df).columns[pd.isnull(clean_data.df).sum() > 0].tolist()
clean_data.fill_numerical_column(column_list)

In [49]:
null_info = DataFrameInfo(clean_data.df)
null_info.get_null_counts()

Bearer Id                         0
Start                             0
Start ms                          0
End                               0
End ms                            0
Dur. (ms)                         0
IMSI                              0
MSISDN/Number                     0
IMEI                              0
Last Location Name                0
Avg RTT DL (ms)                   0
Avg RTT UL (ms)                   0
Avg Bearer TP DL (kbps)           0
Avg Bearer TP UL (kbps)           0
DL TP < 50 Kbps (%)               0
50 Kbps < DL TP < 250 Kbps (%)    0
250 Kbps < DL TP < 1 Mbps (%)     0
DL TP > 1 Mbps (%)                0
UL TP < 10 Kbps (%)               0
10 Kbps < UL TP < 50 Kbps (%)     0
50 Kbps < UL TP < 300 Kbps (%)    0
UL TP > 300 Kbps (%)              0
Activity Duration DL (ms)         0
Activity Duration UL (ms)         0
Handset Manufacturer              0
Handset Type                      0
Nb of sec with Vol DL < 6250B     0
Nb of sec with Vol UL < 1250B     0
Social Media DL (Bytes)           0
Social Media UL (Bytes)           0
Google DL (Bytes)                 0
Google UL (Bytes)                 0
Email DL (Bytes)                  0
Email UL (Bytes)                  0
Youtube DL (Bytes)                0
Youtube UL (Bytes)                0
Netflix DL (Bytes)                0
Netflix UL (Bytes)                0
Gaming DL (Bytes)                 0
Gaming UL (Bytes)                 0
Other DL (Bytes)                  0
Other UL (Bytes)                  0
Total UL (Bytes)                  0
Total DL (Bytes)                  0
dtype: int64

In [50]:
bad_columns = clean_data.get_column_with_many_null()
print("Bad Columns (having more than 30% null values) after cleanup")
print(bad_columns)

Bad Columns (having more than 30% null values) after cleanup
[]

In [51]:
# Convert 'start' and 'end' to datetime

clean_df = clean_data.convert_to_datetime(clean_data.df)

In [52]:
clean_df.dtypes.unique()

array([dtype('float64'), dtype('<M8[ns]'), dtype('O')], dtype=object)

In [53]:
clean_data.df[['Start', 'End']]

                     Start                 End
0      2019-04-04 12:01:00 2019-04-25 14:35:00
1      2019-04-09 13:04:00 2019-04-25 08:15:00
2      2019-04-09 17:42:00 2019-04-25 11:58:00
3      2019-04-10 00:31:00 2019-04-25 07:36:00
4      2019-04-12 20:10:00 2019-04-25 10:40:00
...                    ...                 ...
149995 2019-04-29 07:28:00 2019-04-30 00:01:00
149996 2019-04-29 07:28:00 2019-04-30 06:02:00
149997 2019-04-29 07:28:00 2019-04-30 10:41:00
149998 2019-04-29 07:28:00 2019-04-30 10:46:00
149999 2019-04-29 07:28:00 2019-04-30 10:40:00

[149001 rows x 2 columns]

In [54]:
# Drop duplicates from  dataaet

clean_df = clean_data.drop_duplicate(clean_df)

In [55]:
clean_data.df.head()

,Bearer Id,Start,Start ms,End,End ms,Dur. (ms),IMSI,MSISDN/Number,IMEI,Last Location Name,Avg RTT DL (ms),Avg RTT UL (ms),Avg Bearer TP DL (kbps),Avg Bearer TP UL (kbps),DL TP < 50 Kbps (%),50 Kbps < DL TP < 250 Kbps (%),250 Kbps < DL TP < 1 Mbps (%),DL TP > 1 Mbps (%),UL TP < 10 Kbps (%),10 Kbps < UL TP < 50 Kbps (%),50 Kbps < UL TP < 300 Kbps (%),UL TP > 300 Kbps (%),Activity Duration DL (ms),Activity Duration UL (ms),Handset Manufacturer,Handset Type,Nb of sec with Vol DL < 6250B,Nb of sec with Vol UL < 1250B,Social Media DL (Bytes),Social Media UL (Bytes),Google DL (Bytes),Google UL (Bytes),Email DL (Bytes),Email UL (Bytes),Youtube DL (Bytes),Youtube UL (Bytes),Netflix DL (Bytes),Netflix UL (Bytes),Gaming DL (Bytes),Gaming UL (Bytes),Other DL (Bytes),Other UL (Bytes),Total UL (Bytes),Total DL (Bytes)
0,13114483460844900352.000,2019-04-04 12:01:00,770.000,2019-04-25 14:35:00,662.000,1823652.000,208201448079117.000,33664962239.000,35521209507511.000,9.16456699548519E+015,42.000,5.000,23.000,44.000,100.000,0.000,0.000,0.000,100.000,0.000,0.000,0.000,37624.000,38787.000,Samsung,Samsung Galaxy A5 Sm-A520F,213.000,214.000,1545765.000,24420.000,1634479.000,1271433.000,3563542.000,137762.000,15854611.000,2501332.000,8198936.000,9656251.000,278082303.000,14344150.000,171744450.000,8814393.000,36749741.000,308879636.000
1,13114483482878900224.000,2019-04-09 13:04:00,235.000,2019-04-25 08:15:00,606.000,1365104.000,208201909211140.000,33681854413.000,35794009006359.000,L77566A,65.000,5.000,16.000,26.000,100.000,0.000,0.000,0.000,100.000,0.000,0.000,0.000,168.000,3560.000,Samsung,Samsung Galaxy J5 (Sm-J530),971.000,1022.000,1926113.000,7165.000,3493924.000,920172.000,629046.000,308339.000,20247395.000,19111729.000,18338413.000,17227132.000,608750074.000,1170709.000,526904238.000,15055145.000,53800391.000,653384965.000
2,13114483484080500736.000,2019-04-09 17:42:00,1.000,2019-04-25 11:58:00,652.000,1361762.000,208200314458056.000,33760627129.000,35281510359387.000,D42335A,45.000,5.000,6.000,9.000,100.000,0.000,0.000,0.000,100.000,0.000,0.000,0.000,0.000,0.000,Samsung,Samsung Galaxy A8 (2018),751.000,695.000,1684053.000,42224.000,8535055.000,1694064.000,2690151.000,672973.000,19725661.000,14699576.000,17587794.000,6163408.000,229584621.000,395630.000,410692588.000,4215763.000,27883638.000,279807335.000
3,13114483485442799616.000,2019-04-10 00:31:00,486.000,2019-04-25 07:36:00,171.000,1321509.000,208201402342131.000,33750343200.000,35356610164913.000,T21824A,45.000,5.000,44.000,44.000,100.000,0.000,0.000,0.000,100.000,0.000,0.000,0.000,3330.000,37882.000,undefined,undefined,17.000,207.000,644121.000,13372.000,9023734.000,2788027.000,1439754.000,631229.000,21388122.000,15146643.000,13994646.000,1097942.000,799538153.000,10849722.000,749039933.000,12797283.000,43324218.000,846028530.000
4,13114483499480700928.000,2019-04-12 20:10:00,565.000,2019-04-25 10:40:00,954.000,1089009.000,208201401415120.000,33699795932.000,35407009745539.000,D88865A,45.000,5.000,6.000,9.000,100.000,0.000,0.000,0.000,100.000,0.000,0.000,0.000,0.000,0.000,Samsung,Samsung Sm-G390F,607.000,604.000,862600.000,50188.000,6248284.000,1500559.000,1936496.000,173853.000,15259380.000,18962873.000,17124581.000,415218.000,527707248.000,3529801.000,550709500.000,13910322.000,38542814.000,569138589.000

In [56]:
clean_data.df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 149001 entries, 0 to 149999
Data columns (total 44 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   Bearer Id                       149001 non-null  float64
 1   Start                           149001 non-null  datetime64[ns]
 2   Start ms                        149001 non-null  float64
 3   End                             149001 non-null  datetime64[ns]
 4   End ms                          149001 non-null  float64
 5   Dur. (ms)                       149001 non-null  float64
 6   IMSI                            149001 non-null  float64
 7   MSISDN/Number                   149001 non-null  float64
 8   IMEI                            149001 non-null  float64
 9   Last Location Name              149001 non-null  object
 10  Avg RTT DL (ms)                 149001 non-null  float64
 11  Avg RTT UL (ms)                 149001 non-null  float64
 12  Avg Bearer TP DL (kbps)         149001 non-null  float64
 13  Avg Bearer TP UL (kbps)         149001 non-null  float64
 14  DL TP < 50 Kbps (%)             149001 non-null  float64
 15  50 Kbps < DL TP < 250 Kbps (%)  149001 non-null  float64
 16  250 Kbps < DL TP < 1 Mbps (%)   149001 non-null  float64
 17  DL TP > 1 Mbps (%)              149001 non-null  float64
 18  UL TP < 10 Kbps (%)             149001 non-null  float64
 19  10 Kbps < UL TP < 50 Kbps (%)   149001 non-null  float64
 20  50 Kbps < UL TP < 300 Kbps (%)  149001 non-null  float64
 21  UL TP > 300 Kbps (%)            149001 non-null  float64
 22  Activity Duration DL (ms)       149001 non-null  float64
 23  Activity Duration UL (ms)       149001 non-null  float64
 24  Handset Manufacturer            149001 non-null  object
 25  Handset Type                    149001 non-null  object
 26  Nb of sec with Vol DL < 6250B   149001 non-null  float64
 27  Nb of sec with Vol UL < 1250B   149001 non-null  float64
 28  Social Media DL (Bytes)         149001 non-null  float64
 29  Social Media UL (Bytes)         149001 non-null  float64
 30  Google DL (Bytes)               149001 non-null  float64
 31  Google UL (Bytes)               149001 non-null  float64
 32  Email DL (Bytes)                149001 non-null  float64
 33  Email UL (Bytes)                149001 non-null  float64
 34  Youtube DL (Bytes)              149001 non-null  float64
 35  Youtube UL (Bytes)              149001 non-null  float64
 36  Netflix DL (Bytes)              149001 non-null  float64
 37  Netflix UL (Bytes)              149001 non-null  float64
 38  Gaming DL (Bytes)               149001 non-null  float64
 39  Gaming UL (Bytes)               149001 non-null  float64
 40  Other DL (Bytes)                149001 non-null  float64
 41  Other UL (Bytes)                149001 non-null  float64
 42  Total UL (Bytes)                149001 non-null  float64
 43  Total DL (Bytes)                149001 non-null  float64
dtypes: datetime64[ns](2), float64(39), object(3)
memory usage: 51.2+ MB

In [ ]:
# saving cleaned data
clean_data.df.to_csv("../data/cleaned_data.csv")